/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const WasteEntry = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'mealType' : IDL.Text,
  'foodName' : IDL.Text,
  'reason' : IDL.Text,
});
export const Stats = IDL.Record({
  'mostWastedFood' : IDL.Text,
  'totalWasteThisMonth' : IDL.Float64,
  'totalWaste' : IDL.Float64,
  'totalWasteThisWeek' : IDL.Float64,
});
export const Tip = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTip' : IDL.Func([IDL.Text], [], []),
  'addWasteEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteWasteEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWasteEntries' : IDL.Func([], [IDL.Vec(WasteEntry)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const WasteEntry = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'mealType' : IDL.Text,
    'foodName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Stats = IDL.Record({
    'mostWastedFood' : IDL.Text,
    'totalWasteThisMonth' : IDL.Float64,
    'totalWaste' : IDL.Float64,
    'totalWasteThisWeek' : IDL.Float64,
  });
  const Tip = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTip' : IDL.Func([IDL.Text], [], []),
    'addWasteEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteWasteEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWasteEntries' : IDL.Func([], [IDL.Vec(WasteEntry)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };