/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Stats {
  'mostWastedFood' : string,
  'totalWasteThisMonth' : number,
  'totalWaste' : number,
  'totalWasteThisWeek' : number,
}
export type Time = bigint;
export interface Tip { 'id' : bigint, 'text' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WasteEntry {
  'id' : bigint,
  'owner' : Principal,
  'date' : string,
  'notes' : string,
  'timestamp' : Time,
  'quantity' : number,
  'mealType' : string,
  'foodName' : string,
  'reason' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTip' : ActorMethod<[string], undefined>,
  'addWasteEntry' : ActorMethod<
    [string, number, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteWasteEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWasteEntries' : ActorMethod<[], Array<WasteEntry>>,
  'getStats' : ActorMethod<[], Stats>,
  'getTips' : ActorMethod<[], Array<Tip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];